In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[-1]

9

In [9]:
arr[5:]

array([5, 6, 7, 8, 9])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])


You must explicitly copy the array. If you just assign and make changes then the variable you assign to is just a pointer to the original array.


In [12]:
arr_copy = arr.copy()

In [13]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
arr_2d[2, 1]

8

Grab sub sections of matrix


In [18]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

## Conditional selection

In [21]:
arr2 = np.arange(0, 11)

In [22]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
bool_arr = arr2 > 5

In [25]:
bool_arr

array([ True,  True,  True,  True,  True, False,  True,  True,  True,  True], dtype=bool)

In [30]:
arr2[bool_arr]

array([ 6,  7,  8,  9, 10])

Same thing in one step

In [29]:
arr2[arr2>5]

array([ 6,  7,  8,  9, 10])